### ISSUE TITLE
About dataloader

### ISSUE THREAD

**Issue by xllau** [marcelsheeny/radiate_sdk#1]
Hi, would you like to provide the training and validation dataloader? Since there is not anything find in your SDK.

**Comment by marcelsheeny** [comment]
I added the training code https://github.com/marcelsheeny/radiate_sdk/blob/master/vehicle_detection/train.py

This code has the logic for both horizontal and oriented bounding boxes, however it is not working with oriented bounding boxes since the current version of detectron2 doesn't support training with rotated bboxes (AFAIK).

**Comment by xllau** [comment]
> I added the training code https://github.com/marcelsheeny/radiate_sdk/blob/master/vehicle_detection/train.py
> 
> This code has the logic for both horizontal and oriented bounding boxes, however it is not working with oriented bounding boxes since the current version of detectron2 doesn't support training with rotated bboxes (AFAIK).

Thanks a lot for your update!
And I have applied for your dataset access for few days, hope I can get it sooner!

**Comment by marcelsheeny** [comment]
We are an analysing each request individually and soon we will give you soon access to the dataset.
