### ISSUE TITLE
Labels with Wrong Directions or Inconsistent Sizes

### ISSUE THREAD

**Issue by qiank10** [marcelsheeny/radiate_sdk#13]
Hi authors, 

I plot some radar images with labels and find that there exist two types of errors in the labels. 

First, some labels have wrong heading directions. For example, the car on the right side in the figure below should be towards the left. 
![image](https://user-images.githubusercontent.com/1515092/106374960-b2918180-633c-11eb-8152-75b323fd34f0.png)

Second, the labels of the same car across successive frames have different widths and heights. For some labels, the width is even larger than the height, which is not possible for a real car. 

I guess these labels may impact the recognition performance of models. Do you have a plan to correct them?

Thank you and looking forward to your reply!

**Comment by marcelsheeny** [comment]
We acknowledge that for some annotations the direction and width/height of the car was not corrected labelled. Currently we don't have the plan to fix it, however since we use the DOTA Pascal mAP metric (https://captain-whu.github.io/DOTA/index.html), the "real" orientation and width/height of the car does not really matter for the evaluation.
