### ISSUE TITLE
3D annotations

### ISSUE THREAD

**Issue by MartinHahner** [marcelsheeny/radiate_sdk#18]
Hi Marcel,
thank you for the release of your data!

I am a bit confused regarding the annotations.
I only found 2D (BEV in radar space I guess?) annotations in the `annotation.json` files
but on the [camera visualizations](https://github.com/marcelsheeny/radiate_sdk/blob/master/assets/radiate.png), you show projected 3D bounding boxes. 
Are these just the 2D annotations with a fixed height per class or how does one get these "pseudo" 3D bounding boxes?

I am asking because I want to evaluate 3D Object Detection methods on your Velodyne HDL-32e LiDAR data.

Looking forward to your reply.

Greets, Martin

**Comment by marcelsheeny** [comment]
Hi Martin.

Our dataset only provide 2D BEV bounding boxes. We projected the 2D BEV bounding box to the camera using the estimate heights for each class creating a 3D pseudo bounding box.

The 3D bounding boxes are not really reliable, and since we annotated on the radar images, the different sensor frequencies and the speed of the ego vehicle create distortions on the Lidar annotations.

However If you want to generate the 3D bounding boxes at your own risk, you can see the implementation [here](https://github.com/marcelsheeny/radiate_sdk/blob/a23246888d42e4dad42fd56b0d36ca0dcc836061/radiate.py#L396) on how we did it.

Cheers,
Marcel

**Comment by MartinHahner** [comment]
Thank you for your detailed reply.
